name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'

permissions: read-all

jobs:
  vulncheck:
    name: Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: '1.25.8'

      - name: Run govulncheck
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
          cd awskms && go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
          cd ../gcpkms && go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
          cd ../azurekv && go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
          cd ../vault && go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 ./...
